name: Release

on:
  push:
    tags:
    - "*"

env:
  PACKAGE_NAME: opencl-c-headers
  PACKAGE_DESCRIPTION: OpenCL (Open Computing Language) C header files

jobs:
  release:
    runs-on: ubuntu-latest
    container: streamhpc/opencl-sdk-base:ubuntu-22.04-20230717
    steps:
    - name: Install prerequisites
      shell: bash
      run: apt-get update -qq && apt-get install -y cmake devscripts

    - name: Import GPG signing key
      shell: bash
      run: echo "${{ secrets.DEB_SIGNING_KEY }}" | gpg --import

    - name: Download source code
      shell: bash
      run: wget -O $GITHUB_WORKSPACE/../${{ env.PACKAGE_NAME }}_$GITHUB_REF_NAME.orig.tar.gz https://github.com/$GITHUB_REPOSITORY/archive/refs/tags/$GITHUB_REF_NAME.tar.gz

    - name: Assemble Debian packaging files
      shell: bash
      run: |
        mkdir debian
        echo "Source: opencl-c-headers"                                             >> ./debian/control
        echo "Section: devel"                                                       >> ./debian/control
        echo "Priority: optional"                                                   >> ./debian/control
        echo "Maintainer: ${{ vars.DEB_MAINTAINER }}"                               >> ./debian/control
        echo "Build-Depends: cmake, build-essential"                                >> ./debian/control
        echo "Homepage: https://github.com/KhronosGroup/OpenCL-Headers"             >> ./debian/control
        echo ""                                                                     >> ./debian/control
        echo "Package: opencl-c-headers"                                            >> ./debian/control
        echo "Architecture: any"                                                    >> ./debian/control
        echo "Description: ${{ vars.PACKAGE_DESCRIPTION }}"                         >> ./debian/control

        echo "opencl-c-headers ($GITHUB_REF_NAME-0ppa0) jammy; urgency=low"         >> ./debian/changelog
        echo ""                                                                     >> ./debian/changelog
        echo "  * Released version $GITHUB_REF_NAME"                                >> ./debian/changelog
        echo ""                                                                     >> ./debian/changelog
        echo " -- ${{ vars.DEB_MAINTAINER }}  Tue, 01 Nov 2011 20:32:17 +0100"      >> ./debian/changelog

        echo "#!/usr/bin/make -f"                                                   >> ./debian/rules
        echo "BUILDDIR = build_dir"                                                 >> ./debian/rules
        echo "build:"                                                               >> ./debian/rules
        echo "	mkdir \$(BUILDDIR);"                                                >> ./debian/rules
        echo "	cd \$(BUILDDIR); cmake -DCMAKE_INSTALL_PREFIX=../debian/tmp/usr .." >> ./debian/rules
        echo "	make -C \$(BUILDDIR)"                                               >> ./debian/rules
        echo "binary: binary-indep binary-arch"                                     >> ./debian/rules
        echo "binary-indep:"                                                        >> ./debian/rules
        echo "	# nothing to be done"                                               >> ./debian/rules
        echo "binary-arch:"                                                         >> ./debian/rules
        echo "	cd \$(BUILDDIR); cmake -P cmake_install.cmake"                      >> ./debian/rules
        echo "	mkdir debian/tmp/DEBIAN"                                            >> ./debian/rules
        echo "	dpkg-gencontrol -p${{ env.PACKAGE_NAME }}"                          >> ./debian/rules
        echo "	dpkg --build debian/tmp .."                                         >> ./debian/rules
        echo "clean:"                                                               >> ./debian/rules
        echo "	rm -rf \$(BUILDDIR)"                                                >> ./debian/rules
        echo ".PHONY: binary binary-arch binary-indep clean"                        >> ./debian/rules

    - name: List Debian packaging files
      shell: bash
      run: |
        cat $GITHUB_WORKSPACE/debian/control
        cat $GITHUB_WORKSPACE/debian/changelog
        cat $GITHUB_WORKSPACE/debian/rules

    - name: Build source package
      shell: bash
      run: debuild -S -sa

    - name: Push source package to the PPA
      shell: bash
      run: dput ppa:${{ vars.PPA }} $GITHUB_WORKSPACE/../${{ env.PACKAGE_NAME }}_$GITHUB_REF_NAME-0ppa0_source.changes
