name: Release

on:
  push:
    tags:
    - "*"

env:
  PACKAGE_NAME: opencl-c-headers
  PACKAGE_DESCRIPTION: OpenCL (Open Computing Language) C header files

jobs:
  release:
    runs-on: ubuntu-latest
    container: streamhpc/opencl-sdk-base:ubuntu-22.04-20230717
    steps:
    - name: Install prerequisites
      shell: bash
      run: apt-get update -qq && apt-get install -y cmake devscripts debhelper-compat=13

    - name: Import GPG signing key
      shell: bash
      run: echo "${{ secrets.DEB_SIGNING_KEY }}" | gpg --import

    - name: Download and extract source code
      shell: bash
      run: |
        wget -O $GITHUB_WORKSPACE/${{ env.PACKAGE_NAME }}_$GITHUB_REF_NAME.orig.tar.gz https://github.com/$GITHUB_REPOSITORY/archive/refs/tags/$GITHUB_REF_NAME.tar.gz
        tar -xvf $GITHUB_WORKSPACE/${{ env.PACKAGE_NAME }}_$GITHUB_REF_NAME.orig.tar.gz

    - name: Generate packaging scripts
      shell: bash
      run: cmake -P $GITHUB_WORKSPACE/*/cmake/DebSourcePkg.cmake -D CPACK_DEBIAN_PACKAGE_MAINTAINER="${{vars.DEB_MAINTAINER}}"

    - name: Build source package
      shell: bash
      run: debuild -S -sa

    - name: Push source package to the PPA
      shell: bash
      run: dput ppa:${{ vars.PPA }} $GITHUB_WORKSPACE/../${{ env.PACKAGE_NAME }}_$GITHUB_REF_NAME-1ppa0_source.changes

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
