name: Release

on:
  push:
    tags:
    - "*"
env:
  distroseries: jammy

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      shell: bash
      run: sudo apt-get update -qq && sudo apt-get install -y cmake devscripts debhelper-compat=13

    - name: Import GPG signing key
      shell: bash
      run: echo "${{ secrets.DEB_SIGNING_KEY }}" | gpg --import

    - name: Download and extract source code
      shell: bash
      run: |
        wget -O $GITHUB_WORKSPACE/source.orig.tar.gz https://github.com/$GITHUB_REPOSITORY/archive/refs/tags/$GITHUB_REF_NAME.tar.gz
        tar -xvf $GITHUB_WORKSPACE/source.orig.tar.gz

    - name: Generate packaging scripts
      shell: bash
      run: cmake
        -D ORIG_ARCHIVE=$GITHUB_WORKSPACE/source.orig.tar.gz
        -D LATEST_RELEASE_VERSION=$GITHUB_REF_NAME
        -D DEBIAN_DISTROSERIES=${{ env.distroseries }}
        -D DEBIAN_PACKAGE_MAINTAINER="${{ vars.DEB_MAINTAINER }}"
        -D DEBIAN_VERSION_SUFFIX=${{ vars.DEB_VERSION_SUFFIX }}
        -P $GITHUB_WORKSPACE/OpenCL-Headers*/cmake/DebSourcePkg.cmake

    - name: Build source package
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/OpenCL-Headers*/
        debuild -S -sa

    - name: Push source package to the PPA
      shell: bash
      run: dput ppa:${{ vars.PPA }} $GITHUB_WORKSPACE/*source.changes

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
